"""Memo tab: generate and download a structured investment deal memo."""
from __future__ import annotations

from datetime import datetime, timezone

import streamlit as st

from agents.committee import Committee

_TEMPLATE = """\
# Investment Deal Memo

| Field | Value |
|---|---|
| Basin | **{basin}** |
| Fuel type | {fuel_type_upper} |
| Target year | {target_year} |
| WTI assumption | ${wti}/bbl |
| Verdict | **{verdict}** |
| Conviction | {conviction} |
| Generated | {date} |

*Confidential — Investment Committee Use Only*

---

## Committee Verdict

**{verdict}** — {conviction} conviction

{rationale}

| | |
|---|---|
| **Top opportunity** | {top_opportunity} |
| **Top risk** | {top_risk} |

---

## Bull Case — Riley Chen (Growth Analyst)

{bull_text}

---

## Bear Case — Marcus Webb (Risk Manager)

{bear_text}

---

## PM Deliberation

{pm_text}

---

## Process Notes

| Item | Detail |
|---|---|
| Data sources | EIA Open Data API v2 · FRED WTISPLC |
| Forecasting model | Facebook Prophet — multiplicative seasonality · 0.05 changepoint prior · 80% CI |
| Tool calls executed | {total_tool_calls} |
| Analysis duration | {latency_seconds}s |
| Analysis timestamp | {date} |

---

*This memo was generated by the Energy Intelligence System. All production figures are sourced \
from public EIA / FRED data. Forecasts are directional guidance only and do not constitute a \
reserve study or formal investment recommendation. Independent verification is required before \
capital allocation.*
"""


def _generate_memo(debate_result: dict) -> str:
    meta    = debate_result["metadata"]
    pm_text = debate_result["pm"]["text_response"]
    verdict = Committee.parse_pm_verdict(pm_text)

    return _TEMPLATE.format(
        basin=meta["basin"],
        fuel_type_upper=meta["fuel_type"].upper(),
        target_year=meta["target_year"],
        wti=meta["wti_assumption"],
        date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        verdict=verdict.get("verdict") or "N/A",
        conviction=verdict.get("conviction") or "N/A",
        rationale=verdict.get("rationale") or "_No rationale provided._",
        top_opportunity=verdict.get("top_opportunity") or "N/A",
        top_risk=verdict.get("top_risk") or "N/A",
        bull_text=debate_result["bull"]["text_response"],
        bear_text=debate_result["bear"]["text_response"],
        pm_text=pm_text,
        total_tool_calls=meta.get("total_tool_calls", "N/A"),
        latency_seconds=meta.get("latency_seconds", "N/A"),
    )


def render_memo(basin: str, fuel_type: str, target_year: int) -> None:
    """Render the Memo tab."""
    debate_key = f"debate_{basin}_{fuel_type}_{target_year}"
    memo_key   = f"memo_{basin}_{fuel_type}_{target_year}"

    debate_result = st.session_state.get(debate_key)
    has_committee = debate_result is not None

    if not has_committee:
        st.info(
            "Run the **🏛️ Committee** tab first — the memo is assembled from the "
            "agents' tool-backed arguments and the PM's verdict.",
            icon="ℹ️",
        )

    col_gen, col_dl = st.columns([1, 1])

    with col_gen:
        generate = st.button(
            "📄 Generate Deal Memo",
            type="primary",
            disabled=not has_committee,
            use_container_width=True,
            help="Requires the Investment Committee to be run first.",
        )

    if generate and has_committee:
        with st.spinner("Assembling memo…"):
            memo_md = _generate_memo(debate_result)
        st.session_state[memo_key] = memo_md

    memo_md: str | None = st.session_state.get(memo_key)

    if memo_md:
        filename = (
            f"{basin.lower().replace(' ', '_')}_"
            f"{fuel_type}_{target_year}_deal_memo.md"
        )
        with col_dl:
            st.download_button(
                "⬇️ Download (.md)",
                data=memo_md,
                file_name=filename,
                mime="text/markdown",
                use_container_width=True,
            )

        st.divider()
        st.markdown(memo_md)
